config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chips, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :users do
    resource :wallet
  end

  # mount StripeEvent::Engine, at: '/stripe-webhooks'

  post '/users/:user_id/wallet/update_balance', to: 'wallets#update_balance', as: 'update_balance'

  post "bets/:bet_id/user_bet_create", to: "user_bets#create", as: "user_bet"
  delete 'bets/:id', to: 'bets#destroy', as: 'delete_bet'
end

app/models/chip.rb
class Chip < ApplicationRecord
  monetize :price_cents

end

app/controllers/chips_controller.rb
class ChipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chips = policy_scope(Chip)
  end

end

app/views/chips/index.html.erb
<div class="chips-container">
  <h1>Buy your credits</h1>
</div>
  <div class="row col-12 col-lg-12 img-center">
    <% @chips.each do |chip| %>

      <div class="chips-card" style="width: 20%;  margin: 5">
        <%= form_tag orders_path, method: :post, class: "foorm" do %>
          <%= hidden_field_tag 'chip_id', chip.id %>
          <button type="submit" class="img-center">
            <%= image_tag chip.image_url, class: "card-img-top" %>
          </button>
          <div class="img-center">
            <h5 class="card-title"><p>Amount: R$ <%= chip.name %></p></h5>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>