config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chips, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :users do
    resource :wallet
  end

  # mount StripeEvent::Engine, at: '/stripe-webhooks'

  post '/users/:user_id/wallet/update_balance', to: 'wallets#update_balance', as: 'update_balance'

  post "bets/:bet_id/user_bet_create", to: "user_bets#create", as: "user_bet"
  delete 'bets/:id', to: 'bets#destroy', as: 'delete_bet'
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  has_many :user_bets
  has_many :users, through: :user_bets
  has_one_attached :photo
  after_update :bet_result

  def winners
    winners = self.user_bets.where(answer: self.result)
    prize = self.amount * self.user_bets.count
    winners.each do |winner|
      balance = user.wallet.balance
      winner.user.wallet.update(balance: (balance + (prize / winners.count)))
    end
    self.update_column(:status, "finished")
  end

  def updated_once?
    updated_once
  end

  def bet_result
    winners
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :authenticate_user!


  def index
    @bets = policy_scope(Bet)
  end

  def show
    @bet = Bet.find(params[:id])
    authorize @bet
    # raise
  end

  def new
    if current_user.blank?
      redirect_to new_user_session_path
    end
    @bet = Bet.new
    authorize @bet
  end

  def create
    @bet = Bet.new(bet_params)
    puts bet_params
    @bet.user = current_user
    authorize @bet
      if @bet.save
        redirect_to bets_path(@bet), notice: "Bet was successfully created"
      else
        render :new, status: :unprocessable_entity
      end
  end

  def edit
    @bet = Bet.find(params[:id])
    authorize @bet

    # if @bet.updated_once?
    #   redirect_to bets_path, alert: "Already updated once, contact support"
    # else
    #   render :edit
    # end
  end

  def update
    @bet = Bet.find(params[:id])
    authorize @bet

    if @bet.update(bet_params)
      redirect_to @bet, notice: "Bet was successfully updated"
      # elsif @bet.update(bet_params.merge(updated_once: true))
      # redirect_to bets_path, alert: "Already updated once, contact support"
      # Comentamos para a apresentação.
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy
    redirect_to bets_path
    authorize @bet
  end

  private


  def bet_params
    params.require(:bet).permit(:user, :description, :amount, :start_date, :end_date, :status, :max_users, :photo, :result, :updated_once)
  end

end

app/views/bets/edit.html.erb
<div class="pt-2">
  <%= simple_form_for @bet do |f| %>
  <div class="card text-center">
    <div class="card-header">
      <h1>Edit bet</h1>
    </div>
  </div>
  <br>
    <%= f.input :description, disabled: true %>
    <%= f.input :result, label: 'Result: Check for true, uncheck for false', as: :radio_buttons %>
    <div class="d-grid gap-2">
      <%= f.submit class: "btn btn-flat" %>
    </div>
  <% end %>
  <div class="text-center">
    <%= link_to "Back to list", bets_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/bets/index.html.erb
<div class="index-cards">
  <div class="pt-4">
    <h1>Dashboard</h1>
    <h5>Welcome, <%= current_user.email %>!</h5>
    <%# add name a name column to users %>
  </div>

  <section class="d-flex justify-content-center pb-4">
    <a href="/users/:user_id/wallet" class="data-card">
      <h3>Balance</h3>
      <h4>R$<%= current_user&.wallet&.balance %></h4>
      <p>Go to your wallet</p>
      <span class="link-text d-flex justify-content-end">
        <%# Buy chips %>
        <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#FF0032"/>
        </svg>
      </span>
    </a>
  </section>

 <section class="d-flex justify-content-center">
    <div class="articles pb-4">
      <% @bets.each do |bet| %>
        <div class="article-wrapper">
          <article>
            <figure>
              <% if bet.photo.attached? %>
                <%= cl_image_tag(bet.photo.key, crop: :fill) %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
              <% end %>
            </figure>
            <div class="article-body">
              <h2>Description:</h2>
              <p><%= bet.description %></p>
                <ul class="list-group list-group-flush">
                  <p>
                    <li class="list-group-item">Amount: R$<%= bet.amount %></li>
                    <li class="list-group-item">Status: <%= bet.status %></li>
                  </p>
                </ul>
              <a href="<%= bet_path(bet.id) %>" class="d-flex justify-content-end">
                <p><span class="sr-only">See more</span></p>
                <svg class="icon" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
              </a>
            </div>
          </article>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/bets/new.html.erb
<div class="pt-1">
  <%= simple_form_for [@bet], html: { class: "bet-form" }, data: { controller: 'flatpickr' } do |f| %>
    <div class="card text-center">
      <div class="card-header">
        <h1>Create bet</h1>
      </div>
    </div>
    <br>
    <%= f.input :description %>
    <%= f.input :amount, collection: 10..100,:input_html => { :class => 'form-control'}, :label => 'Amount' %>
    <%= f.input :status, :as => :hidden, :input_html => { :value => "Open" } %>
    <%= f.input :max_users, collection: 1..10,:input_html => { :class => 'form-control'}, :label => 'Max users' %>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
    <%= f.input :photo, as: :file %>
    <div class="d-grid gap-2">
      <%= f.submit 'Create', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bets/show.html.erb
<div class="chips-container">
  <h1>Bet</h1>
</div>

<div class="show-container" >
  <div class="card" style="width: 30rem; border-radius: 20px; box-shadow: 0 0 15px rgba(0,0,0,0.4);">
    <%# <img src="..." class="card-img-top" alt="..."> %>
      <% if @bet.photo.attached? %>
        <%= cl_image_tag(@bet.photo.key, crop: :fill) %>
      <% else %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="border-radius: 20px "/>
      <% end %>
    <div class="card-body" style= "color: red; font-weight: bold;">
      <h5 class="card-title"><p>Description:</p></h5>
      <p class="card-text"><%= @bet.description %></p>
    </div>
    <div style="padding: 50px;" >
      <ul class="list-group list-group-flush"  >
        <li class="list-group-item" style= "color: #606164;"><p>Amount: R$<%= @bet.amount %></p></li>
        <li class="list-group-item" style= "color: #606164;"><p>Result: <%= @bet.result %></p></li>
        <li class="list-group-item" style= "color: #606164;"><p>Status: <%= @bet.status %></p></li>
        <li class="list-group-item" style= "color: #606164;"><p>Max users: <%= @bet.max_users %></p></li>
        <li class="list-group-item" style= "color: #606164;"><p>Start date: <%= @bet.start_date %></p></li>
        <li class="list-group-item" style= "color: #606164;"><p>End date: <%= @bet.end_date %></p></li>
        <li class="list-group-item" style= "color: #606164; padding: 10px"><p>Total prize: <%= @bet.user_bets.count * @bet.amount %></p></li>
      </ul>
      <div class="d-flex justify-content-center">
        <form action= <%= "/bets/#{@bet.id}/user_bet_create" %> method="post">
          <button name="answer" value="true" class="btn-show" style="border-radius: 10px;"<%= (UserBet.where(user_id: current_user.id, bet_id: @bet.id).present? || (current_user.wallet.balance < @bet.amount) || !(@bet.start_date..@bet.end_date).cover?(Date.today)) ? "disabled" : "" %>>Bet for true</button>
          <button name="answer" value="false" class="btn-show" style="border-radius: 10px "<%= (UserBet.where(user_id: current_user.id, bet_id: @bet.id).present? || (current_user.wallet.balance < @bet.amount) || !(@bet.start_date..@bet.end_date).cover?(Date.today)) ? "disabled" : "" %>>Bet for false</button>
        </form>
      </div>
      <%# <div class="vote-card"> %>
      <div>
        <% if UserBet.where(user_id: current_user.id, bet_id: @bet.id).present? %>
          <p>Voted by:</p>
          <% @bet.user_bets.each do |user_bet| %>
            <p><%= user_bet.user.email %></p>
            <p><%= user_bet.answer %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
<%# <button class="btn btn-primary"><%= link_to "Back", bets_path %>
  <%=  link_to "Back", bets_path, style: " padding: 10px; margin: 20px; text-decoration: none; color: white; background-color: #606164; width: 80px; height; 35px; text-align: center; border-radius: 8px; background-color: #FF0032 " %></p>
  <% if policy(@bet).destroy? %>
    <%= link_to "Delete", delete_bet_path(@bet.id),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: " padding: 10px; margin: 20px; text-decoration: none; color: white; background-color: #606164; width: 80px; height; 35px; text-align: center; border-radius: 8px; background-color: #FF0032 " %>
  <% end %>
  <% if policy(@bet).edit? %>
    <%= link_to "Result", edit_bet_path(@bet.id), style: " padding: 10px; margin: 20px; text-decoration: none; color: white; background-color: #606164; width: 80px; height; 35px; text-align: center; border-radius: 8px; background-color: #FF0032 " %>
  <% end %>
</div>