config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chips, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :users do
    resource :wallet
  end

  # mount StripeEvent::Engine, at: '/stripe-webhooks'

  post '/users/:user_id/wallet/update_balance', to: 'wallets#update_balance', as: 'update_balance'

  post "bets/:bet_id/user_bet_create", to: "user_bets#create", as: "user_bet"
  delete 'bets/:id', to: 'bets#destroy', as: 'delete_bet'
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  attribute :balance, :integer, default: 0
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def show
    @wallet = current_user.wallet
    authorize @wallet
  end

  def update
    @wallet = Wallet.find_by(user_id: params[:user_id])
    authorize @wallet
    old_balance = @wallet.balance
    if @wallet.update(wallet_params)
      withdraw_amount = @wallet.withdraw_amount
      new_balance = old_balance - withdraw_amount
      @wallet.update(balance: new_balance, withdraw_amount:0)
      # @wallet.update(balance: new_balance, withdraw_amount:0)
      redirect_to user_wallet_path(current_user)
    else
      render :show
    end
  end

  private

  def wallet_params
    params.require(:wallet).permit(:withdraw_amount)
  end

  # def update_balance
  #   @wallet = Wallet.find_by(user_id: params[:user_id])
  #   authorize @wallet
  #   amount = params[:amount].to_i
  #   @wallet.balance += amount
  #   if @wallet.save
  #     flash[:notice] = "Balance updated successfully."
  #   else
  #     flash[:error] = "Failed to update balance."
  #   end
  #   redirect_to user_wallet_path(current_user)
  # end

  # def update_balance(amount)
  #   @wallet = Wallet.find_by(user: current_user)
  #   authorize @wallet
  #   balance = @wallet.balance
  #   @wallet.update(balance: (balance + amount))
  # end

end

# def show
#   if current_user.signed_in?
#   @wallet = current_user.wallet
#   else
#     redirect_to new_user_session_path
#   end
#   authorize @wallet
# end

app/views/wallets/show.html.erb
<div class="pt-1">
  <div class="balance-card">
    <div class="card text-center">
      <div class="card-header">
        <h1>Wallet</h1>
      </div>
      <div class="card-body">
        <h5 class="text-center">Current Balance:</h5>
        <p class="card-text">R$ <%= @wallet.balance %></p>
      </div>
    </div>
    <div class="d-grid gap-2">
      <a href="/chips" class="btn btn-primary">Buy Chips</a>
      <%# <%= link_to '<button type="submit" class="btn btn-primary">Buy Chips</button>'.html_safe, chips_path %>
      <%# <button type="submit" class="btn btn-primary"><a href="/chips">Buy Chips</a></button> %>
    </div>
  </div>

  <%= simple_form_for [current_user, @wallet], html: { class: "withdraw-card" } do |f| %>
    <div class="card text-center">
      <div class="card-header">
        <h1>Withdraw</h1>
      </div>
    </div>
    <br>
    <div class="mb-3">
      <label class="wallet-form-label">Account Name</label>
      <input type="text" class="wallet-form-control">
    </div>

    <div class="mb-3">
      <label class="wallet-form-label">Bank Name</label>
      <div class="withdraw-select">
        <select>
          <option></option>
          <option>Banco do Brasil</option>
          <option>Bradesco</option>
          <option>Santander</option>
          <option>Itaú</option>
          <option>Caixa Econômica Federal</option>
        </select>
      </div>
    </div>

    <div class="mb-3">
      <label class="wallet-form-label">Account Type</label>
      <div class="withdraw-select">
        <select>
          <option></option>
          <option>Corrente</option>
          <option>Poupança</option>
        </select>
      </div>
    </div>

    <div class="mb-3">
      <label class="wallet-form-label">Bank Code</label>
      <input type="num" class="wallet-form-control" maxlength="4" />
    </div>

    <div class="mb-3">
      <label class="wallet-form-label">Account number</label>
      <input type="num" class="wallet-form-control" maxlength="8" />
    </div>

    <div class="mb-3">
      <label class="wallet-form-label">ID Number</label>
      <input type="num" class="wallet-form-control" maxlength="11" />
    </div>
    <div class="withdraw-label">
      <%= f.input :withdraw_amount, :input_html => { :class => 'withdraw-form-control', autocomplete: 'off'}, :label => 'Withdraw amount' %>
      <%# <%= f.input :withdraw_amount, collection: [20, 50, 100, 200, 500, 1000, 1500, 2000] %>
      <div class="d-grid gap-2">
        <%= f.submit 'Withdraw', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>